// <auto-generated />
using System;
using Matsedeln.Utils;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Matsedeln.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227191041_SeparatedLunchAndDinner")]
    partial class SeparatedLunchAndDinner
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Matsedeln.Models.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GramsPerDeciliter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GramsPerStick")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("Matsedeln.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("RecipeId1")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("g");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("RecipeId");

                    b.HasIndex("RecipeId1");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("Matsedeln.Models.MenuEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DinnerRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("LunchRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DinnerRecipeId");

                    b.HasIndex("LunchRecipeId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("Matsedeln.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentRecipeId");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("Matsedeln.Models.Ingredient", b =>
                {
                    b.HasOne("Matsedeln.Models.Goods", "Good")
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matsedeln.Models.Recipe", "Recipe")
                        .WithMany()
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Matsedeln.Models.Recipe", null)
                        .WithMany("Ingredientlist")
                        .HasForeignKey("RecipeId1");

                    b.Navigation("Good");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("Matsedeln.Models.MenuEntry", b =>
                {
                    b.HasOne("Matsedeln.Models.Recipe", "DinnerRecipe")
                        .WithMany()
                        .HasForeignKey("DinnerRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Matsedeln.Models.Recipe", "LunchRecipe")
                        .WithMany()
                        .HasForeignKey("LunchRecipeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DinnerRecipe");

                    b.Navigation("LunchRecipe");
                });

            modelBuilder.Entity("Matsedeln.Models.Recipe", b =>
                {
                    b.HasOne("Matsedeln.Models.Recipe", "ParentRecipe")
                        .WithMany("ChildRecipes")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("Matsedeln.Models.Recipe", b =>
                {
                    b.Navigation("ChildRecipes");

                    b.Navigation("Ingredientlist");
                });
#pragma warning restore 612, 618
        }
    }
}
