// <auto-generated />
using System;
using MatsedelnShared;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Matserver.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MatsedelnShared.Models.Goods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GramsPerDeciliter")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("GramsPerStick")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Goods");
                });

            modelBuilder.Entity("MatsedelnShared.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoodsId")
                        .HasColumnType("int");

                    b.Property<double>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("float")
                        .HasDefaultValue(0.0);

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("g");

                    b.HasKey("Id");

                    b.HasIndex("GoodsId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("MatsedelnShared.Models.MenuEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DinnerRecipeId")
                        .HasColumnType("int");

                    b.Property<int?>("LunchRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DinnerRecipeId");

                    b.HasIndex("LunchRecipeId");

                    b.ToTable("MenuItems");
                });

            modelBuilder.Entity("MatsedelnShared.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("MatsedelnShared.Models.RecipeHierarchy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildRecipeId")
                        .HasColumnType("int");

                    b.Property<int>("ParentRecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildRecipeId");

                    b.HasIndex("ParentRecipeId");

                    b.ToTable("RecipeHierarchies");
                });

            modelBuilder.Entity("MatsedelnShared.Models.Ingredient", b =>
                {
                    b.HasOne("MatsedelnShared.Models.Goods", "Good")
                        .WithMany()
                        .HasForeignKey("GoodsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatsedelnShared.Models.Recipe", "Recipe")
                        .WithMany("Ingredientlist")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Good");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("MatsedelnShared.Models.MenuEntry", b =>
                {
                    b.HasOne("MatsedelnShared.Models.Recipe", "DinnerRecipe")
                        .WithMany()
                        .HasForeignKey("DinnerRecipeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("MatsedelnShared.Models.Recipe", "LunchRecipe")
                        .WithMany()
                        .HasForeignKey("LunchRecipeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DinnerRecipe");

                    b.Navigation("LunchRecipe");
                });

            modelBuilder.Entity("MatsedelnShared.Models.RecipeHierarchy", b =>
                {
                    b.HasOne("MatsedelnShared.Models.Recipe", "ChildRecipe")
                        .WithMany("ParentRecipes")
                        .HasForeignKey("ChildRecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MatsedelnShared.Models.Recipe", "ParentRecipe")
                        .WithMany("ChildRecipes")
                        .HasForeignKey("ParentRecipeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ChildRecipe");

                    b.Navigation("ParentRecipe");
                });

            modelBuilder.Entity("MatsedelnShared.Models.Recipe", b =>
                {
                    b.Navigation("ChildRecipes");

                    b.Navigation("Ingredientlist");

                    b.Navigation("ParentRecipes");
                });
#pragma warning restore 612, 618
        }
    }
}
